"""
Fibonacci problem

AUTHOR: DISUKHI AHMED

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first  terms will be:
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""


firstNum = 1

secondNum = 2

sumEven = 0
while firstNum <= 400000:
    if firstNum % 2 == 0:
        sumEven += firstNum
    secondNum = firstNum + secondNum
    firstNum = secondNum

print(sumEven)

